name: Release

on:
    workflow_dispatch:

env:
    CHECKOUT_SUBMODULES: ""

jobs:
    release:
        runs-on: ubuntu-latest

        permissions:
            contents: write
            packages: write
            issues: write
            pull-requests: write
            id-token: write

        if: ${{ github.event.workflow_run.conclusion == 'success' }}

        steps:
            -   name: Generate token
                id: get_workflow_token
                uses: actions/create-github-app-token@v1
                with:
                    app-id: ${{ secrets.APPLICATION_ID }}
                    private-key: ${{ secrets.APPLICATION_PRIVATE_KEY }}

            -   uses: actions/checkout@v4
                with:
                    fetch-depth: 0
                    persist-credentials: false
                    token: ${{ steps.get_workflow_token.outputs.token }}
                    submodules: ${{ env.CHECKOUT_SUBMODULES }}

            -   name: Install pnpm
                uses: pnpm/action-setup@v3
                with:
                    version: 8

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.1
                    coverage: none
                env:
                    COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            # semantic release local configuration needs to call ./vendor/bin/monorepo-builder
            -   uses: "ramsey/composer-install@v2"

            -   name: Installing dependencies
                run: pnpm install

            -   name: Semantic Release
                uses: cycjimmy/semantic-release-action@v4
                env:
                    GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
                with:
                    semantic_version: 23